<?xml version="1.0"?>
<package format="3">
  <name>vehicle_control</name><version>0.0.1</version>
  <description>Vehicle speed, steering, and safety control.</description>
  <maintainer email="maintainer@example.com">vehicle_team</maintainer><license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend><depend>rclpy</depend><depend>ackermann_msgs</depend><depend>vehicle_interfaces</depend>
  <export><build_type>ament_python</build_type></export>
  <depend>geometry_msgs</depend>
  <depend>std_srvs</depend>
  <test_depend>python3-pytest</test_depend>

  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_dwb_controller</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>vehicle_planning</exec_depend>

</package>
